# Generated by Django 2.2.13 on 2020-06-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageApp', '0002_auto_20200628_0820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persondata',
            name='days_attended',
        ),
        migrations.RemoveField(
            model_name='persondata',
            name='person',
        ),
        migrations.RemoveField(
            model_name='persondata',
            name='salary',
        ),
        migrations.AddField(
            model_name='person',
            name='days_attended',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='salary',
            field=models.IntegerField(null=True),
        ),
    ]
